### ISSUE TITLE
Compatibility with the custom button card

### ISSUE THREAD

**Issue by genehand** [thomasloven/hass-custom_icons#3]
Hey thanks for all the great work, just found this and switching over from hass-fontawesome.  I may have found a bug when using this with the [custom button card](https://github.com/custom-cards/button-card).  I have a card like this:

```yaml
type: custom:button-card
entity: light.kitchen
icon: "[[[ return variables[entity.state]; ]]]"
variables:
  "on": custom:bulb-group-ceiling-flush-circular
  "off": mdi:faucet-variant
```

When the light turns on, the icon changes as expected.  However now when turning it back off, the icon doesn't change until I refresh the page.  I've cleared the browser cache etc and get this consistently.  

If I use another custom icon for the "off" state, everything works.
